### ISSUE TITLE
Feedback on concatenate()

### ISSUE THREAD

**Issue by grst** [scverse/spatialdata#541] opened 2024-04-08 10:00 UTC
While I in the end was able to concatenate the data the way I like, the user experience wasn't as great as I had hoped, so wanted to drop some feedback. As I'm not that familiar with spatialdata yet, it might be that there are already better solutions -- please let me know if there are. 

### Starting situation
I have ~20 Visium Cytassist samples from a clinical trial processed with nf-core/spatialtranscriptomics (using the https://github.com/nf-core/spatialtranscriptomics/pull/67 branch that already uses spatialdata). The pipeline generates a single `.zarr` folder for each sample. 

### Desired outcome
I would like to have all samples in a single SpatialData object. The AnnData table should contain the gene expression from all samples. 

### Pain points

 * `sd.concatenate` enforces that the input is a list. Is there a reason this can't accept any `Sequence` type (e.g. `dict_values`)?
 * Usually, I pass a dictionary `sample_id -> AnnData` to `anndata.concat`, which nicely makes unique obs_names in combination with `concat(..., index_unique="_")`. This doesn't work with spatialdata.concatenate, which leaves me with either manipulating the `obs_names` for each object before concatenation, or ugly obs names with numeric sufficies (e.g. `AACTCAACCTTGACCA-1_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0`). IMO it would be great to support a dict as input to spatialdata.concatenate, too. 
 * The per-sample SpatialData objects all have the same names for images, shapes and coordinate systems. I currently rename them like this: 
   ```python
   sdatas_vis = {}
  
   for _, row in tqdm(samplesheet.iterrows(), total=samplesheet.shape[0]):
      sample = row["sample"]
      tmp_sd = sd.read_zarr(sample_path / sample / "data" / "sdata_processed.zarr")
      tmp_sd.tables["table"].obs = tmp_sd.tables["table"].obs.assign(**row)
      tmp_sd.tables["table"].obs["region"] = sample
      tmp_sd.tables["table"].uns["spatialdata_attrs"]["region"] = sample
      # rename images
      tmp_sd.images[f"{sample}_hires"] = tmp_sd.images["visium_hires_image"]
      tmp_sd.images[f"{sample}_lowres"] = tmp_sd.images["visium_lowres_image"]
      del tmp_sd.images["visium_hires_image"]
      del tmp_sd.images["visium_lowres_image"]
      # rename shapes
      tmp_sd.shapes[f"{sample}"] = tmp_sd.shapes["visium"]
      del tmp_sd.shapes["visium"]
  
      sdatas_vis[sample] = tmp_sd
   ```
    
    which seems a bit cumbersome. I'm wondering if there's a better solution or what's the intended way of handling such cases. It could also be worth adding a process to the nf-core/spatialtranscriptomics pipeline that already does the concatenation step.

**Comment by melonora** [comment] 2024-04-15 13:12
I am a bit swamped at the moment, but I will look into implementing your suggestions. As you said it would be worthwhile to handle dicts.

**Comment by wangjiawen2013** [comment] 2024-08-06 03:00
I have the same issue !
The per-sample SpatialData objects all have the same names for images, shapes and coordinate systems. So when I concatenate them, an keyerror occurred: `KeyError: 'Images must have unique names across the SpatialData objects to concatenate'`

**Comment by wangjiawen2013** [comment] 2024-08-06 03:05
And it's better to have a way to retrieve (subset) each objects from the concatenated objects.

**Comment by LucaMarconato** [comment] 2024-08-06 11:42
@wangjiawen2013 does `SpatialData.subset()` works for your use case or you would improve something?

**Comment by wangjiawen2013** [comment] 2024-08-07 02:50
What I mean is how to concatenate multi spatialdata objects and subset each objects from the concatenated objects again. The SpatialData objects from xenium all have the same names for images, shapes and coordinate systems, so I cannot concatenate them because `KeyError: Images must have unique names across the SpatialData objects to concatenate`. 
`SpatialData.subset()` can only get elements, not objects.
We can concatenate and subset anndata objects well, what i mean is to concatenate and subset spatialdata objects like anndata objects.

**Comment by LucaMarconato** [comment] 2024-10-01 15:57
@grst 
> The per-sample SpatialData objects all have the same names for images, shapes and coordinate systems. I currently rename them like this:
> ```
> ...
> ```
> which seems a bit cumbersome. I'm wondering if there's a better solution or what's the intended way of handling such cases. It could also be worth adding a process to the nf-core/spatialtranscriptomics pipeline that already does the concatenation step.

@wangjiawen2013 
> I have the same issue !
The per-sample SpatialData objects all have the same names for images, shapes and coordinate systems. So when I concatenate them, an keyerror occurred: KeyError: 'Images must have unique names across the SpatialData objects to concatenate'

Currently what you implemented is basically I would do it. An idea would be to wrap that into an official helper function, or have the `concatenate()` function doing this automatically (contributions are appreciated!). But in the long term our approach would be to allow the user to have nested NGFF hierarchies https://github.com/scverse/spatialdata/issues/398. This would solve the problem with unique names because the new element name would be its relative path to the NGFF store root (`sample0/image` would be different from `sample1/image`).

**Comment by LucaMarconato** [comment] 2024-10-01 15:58
> sd.concatenate enforces that the input is a list. Is there a reason this can't accept any Sequence type (e.g. dict_values)?
> 
> Usually, I pass a dictionary sample_id -> AnnData to anndata.concat, which nicely makes unique obs_names in combination with concat(..., index_unique="_"). This doesn't work with spatialdata.concatenate, which leaves me with either manipulating the obs_names for each object before concatenation, or ugly obs names with numeric sufficies (e.g. AACTCAACCTTGACCA-1_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0). IMO it would be great to support a dict as input to spatialdata.concatenate, too.

- [ ] I'll try to fix these two points.

**Comment by LucaMarconato** [comment] 2024-10-01 16:29
> Usually, I pass a dictionary sample_id -> AnnData to anndata.concat, which nicely makes unique obs_names in combination with concat(..., index_unique="_"). This doesn't work with spatialdata.concatenate, which leaves me with either manipulating the obs_names for each object before concatenation, or ugly obs names with numeric sufficies (e.g. AACTCAACCTTGACCA-1_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0). IMO it would be great to support a dict as input to spatialdata.concatenate, too.

I could make a fix for this, but this falls into a larger discussion. In `spatialdata` we don't use the `.obs` names for a series of reasons:
1. what maps the table rows to some geometries is the pair (region, instance_id), the `obs` index is not enough, so we don't use it. What we use are the columns named after the `region_key` and `instance_key` values.
2. we needed the `obs` indices to be integers, but `AnnData` only supported strings.

So, I could make a fix for this, but the renaming of the `obs` would come for convenience, but not be used in any other `spatialdata` API.

**Comment by LucaMarconato** [comment] 2024-10-02 20:42
Ok actually I have implemented all the above. @wangjiawen2013 @grst it would be great if you could try this out please 😊

**Comment by wangjiawen2013** [comment] 2024-10-03 02:02
Good news! I'll try later.

**Closed** 2024-10-04 13:09 UTC
Labels: enhancement ✨, method: concatenate

**Comment by wangjiawen2013** [comment] 2024-10-17 02:13
Is this implementation released in the current sptial-data version ?

**Comment by LucaMarconato** [comment] 2024-11-11 14:47
Yes, it's available in the released version.

**Comment by Pancreas-Pratik** [comment] 2024-11-24 23:44
> Ok actually I have implemented all the above. [@wangjiawen2013](https://github.com/wangjiawen2013) [@grst](https://github.com/grst) it would be great if you could try this out please 😊

Thank you @LucaMarconato. I can confirm these new improvements work. This saved me a bunch of time!

I was unsure for a while on _exactly_ what to do for merging two Xenium datasets together with identical element names. I had to learn some of the `SpatialData` terminology which really was just learning what the term `element` was referring to. Thank you for the design documentation which helped with learning the terminology (https://spatialdata.scverse.org/en/latest/design_doc.html#elements).

I also had to look through the `Files changed` tab on https://github.com/scverse/spatialdata/pull/720 and view the notes you had written about these new changes. The notes explained that a `dict` had to be used as input within `spatialdata.concatenate()`, which would let SpatialData know what to use for appending unique sample ID suffixes in order to generate a merged object with unique element names successfully (without the `KeyError: Images...` @wangjiawen2013 mentioned above https://github.com/scverse/spatialdata/issues/541#issuecomment-2272515936). For maybe someone who was stuck like I was, what was suggested above in the above comment https://github.com/scverse/spatialdata/issues/541#issuecomment-2386381664 is what what is now implemented within spatialdata.

For me (using two `xenium` datasets) this now looks like:

Loading both `xenium` datasets:
```
from spatialdata_io import xenium

first_sdata = xenium('./data/first_xenium_dataset/outs/')
second_sdata = xenium('./data/second_xenium_dataset/outs/')
```

Creating the `dicts` to be used for appending suffixes to each object's elements to ensure unique element names and prevent `KeyError: Images...` when using `spatialdata.concatenate()`:
```
first_second_dict = {
    'first': first_sdata,
    'second': second_sdata
}
```

and then finally, merge:
```
import spatialdata as sd
fs_sdata=sd.concatenate(first_second_dict)
```

**Comment by wangjiawen2013** [comment] 2024-11-28 07:57
This feature maybe useful when we compare two samples. If we don't merge the two datasets, we cannot assign the same color to the same cell type easily, and it's impossible to compare cellular niches (i.e., regions with distinct compositions of cell types)
https://monkeybread.readthedocs.io/en/latest/index.html

**Comment by wangjiawen2013** [comment] 2024-11-28 08:51
The display of `sdata.table` can be re-formatted:
![Image](https://github.com/user-attachments/assets/88a24557-327a-499e-9fbe-a67058495447)

**Comment by wangjiawen2013** [comment] 2024-11-28 13:01
Hi,
Another question, How to separate or subset each object from the concatenated object ?



在 2024-11-25 07:45:04，"Pratik Mehta" ***@***.***> 写道：

Ok actually I have implemented all the above. @***@***.*** it would be great if you could try this out please 😊

Thank you @LucaMarconato. I can confirm these new improvements work. This saved me a bunch of time!

I was unsure for a while on exactly what to do for merging two Xenium datasets together with identical element names. I had to learn some of the SpatialData terminology which really was just learning what the term element was referring to. Thank you for the design documentation which helped with learning the terminology (https://spatialdata.scverse.org/en/latest/design_doc.html#elements).

I also had to look through the Files changed tab on #720 and view the notes you had written about these new changes. The notes explained that a dict had to be used as input within spatialdata.concatenate(), which would let SpatialData know what to use for appending unique sample ID suffixes in order to generate a merged object with unique element names successfully (without the KeyError: ***@***.*** mentioned above #541 (comment)). For maybe someone who was stuck like I was, what was suggested above in the above comment #541 (comment) is what what is now implemented within spatialdata.

For me (using two xenium datasets) this now looks like:

Loading both xenium datasets:

from spatialdata_io import xenium

first_sdata = xenium('./data/first_xenium_dataset/outs/')
second_sdata = xenium('./data/second_xenium_dataset/outs/')


Creating the dicts to be used for appending suffixes to each object's elements to ensure unique element names and prevent KeyError: Images... when using spatialdata.concatenate():

first_second_dict = {
    'first': first_sdata,
    'second': second_sdata
}


and then finally, merge:

import spatialdata as sd
fs_sdata=sd.concatenate(first_second_dict)

**Comment by LucaMarconato** [comment] 2025-02-12 12:08
> This feature maybe useful when we compare two samples. If we don't merge the two datasets, we cannot assign the same color to the same cell type easily,

Thanks for reporting, it's our goal to fix it in `spatialdata-plot`, but for the moment concatenating is a good way to address the issue.
