### ISSUE TITLE
`transform()` function rotates shapes incorrectly -> incorrect extend

### ISSUE THREAD

**Issue by timtreis** [scverse/spatialdata#353] opened 2023-09-11 21:50 UTC
MRE
```
import geopandas as gpd
import spatialdata
import spatialdata_plot
from shapely import MultiPolygon, Point, Polygon

points = []
for p in [[0, 0], [0, 1], [1, 1], [1, 0]]:
    points.append(Point(p))

gdf = gpd.GeoDataFrame(geometry=points)
gdf["radius"] = 0.05
circles_df = ShapesModel.parse(gdf)
sdata = spatialdata.SpatialData(shapes={"circles": circles_df})

theta = math.pi / 4
rotation = Affine(
[
    [math.cos(theta), -math.sin(theta), 0],
    [math.sin(theta), math.cos(theta), 0],
    [0, 0, 1],
],
input_axes=("x", "y"),
output_axes=("x", "y"),
)
set_transformation(element=sdata["circles"], transformation=rotation, to_coordinate_system="transformed")

sdata.pl.render_shapes().pl.show()

for cs in ["global", "transformed"]:
    print(cs, get_extent(sdata, coordinate_system=cs))
```
Produces the following plot:
<img width="693" alt="image" src="https://github.com/scverse/spatialdata/assets/12818242/0f28953e-fa82-4972-85ae-ba0f665720f3">

We expect the axis of the `transformed` plot to also touch the circles. This is not the case since the extent is calculated to `transformed {'y': (-0.07071067811865475, 1.48492424049175), 'x': (-0.7778174593052023, 0.7778174593052024)}`.

However, the error doesn't come from the extent calculation, but from L305 in `_compute_extent_in_coordinate_system`:
<img width="671" alt="image" src="https://github.com/scverse/spatialdata/assets/12818242/c61c23cf-c26d-4241-9203-886df2f2ce13">

Bounding box before and after transformation: 
<img width="235" alt="image" src="https://github.com/scverse/spatialdata/assets/12818242/fcfdafcf-09fb-435d-92f2-8f017c51bdfc">

Since we're rotating by 45°, we'd expect them to be
```
[ 0,      0]
[−0.7071, 0.7071]
[ 0,      1.4142]
[ 0.7071, 0.7071]
```
(+/- the radius of the circle 0.05) which would result in a different bounding box. With larger radii, the inaccuracy becomes bigger

radius = 0.5

<img width="270" alt="image" src="https://github.com/scverse/spatialdata/assets/12818242/9de9c773-77bf-4e4f-a0ab-8290435dffb6">

**Comment by LucaMarconato** [comment] 2023-10-09 13:50
Quick question @timtreis. Running the code produces this: 
![image](https://github.com/scverse/spatialdata/assets/2664412/720defa4-65c2-4a7d-a25b-ce13271f5e80)

I think I need to use one of the new branches of `spatialdata-plot` that will make it into the next release. Which one?

**Comment by LucaMarconato** [comment] 2023-10-09 13:51
I guess https://github.com/scverse/spatialdata-plot/pull/162, gonna try now.

**Comment by timtreis** [comment] 2023-10-09 14:04
Yes, this one. Can you reproduce?

**Comment by LucaMarconato** [comment] 2023-10-09 14:08
Yes thanks. This is the cause of the bug:
<img width="785" alt="image" src="https://github.com/scverse/spatialdata/assets/2664412/eb00c671-7733-4a64-8873-687b052ad236">

**Comment by timtreis** [comment] 2023-10-09 14:14
Ahhh yeah, makes sense. That's why it scales with `r`

**Comment by LucaMarconato** [comment] 2023-10-09 14:16
The current approach works for raster data, the affected part is points, shapes and polygons. I will implement the exact calculation for the vector data, enabled by default, but I will also make it optional with a parameter of get_extent.

I suspect that the current implementation can be a lot faster since it doesn't need to transform the data, and for most cases actually one doesn't need the exact extent.

**Comment by LucaMarconato** [comment] 2023-10-09 17:01
Fixed 
![image](https://github.com/scverse/spatialdata/assets/2664412/a72be946-217f-4681-a6ad-3df98e22772f)
Gonna make a PR to the `get_extent()` PR, I will also fix the failing tests.

**Comment by LucaMarconato** [comment] 2023-10-09 17:52
I am adding tests, not just for circles but also for points, polygons and multipolygons. 

These are the plots that one would get with the **old code** (note that I have changed the positions of the circles in the "global" coordinate system).
4 circles
![image](https://github.com/scverse/spatialdata/assets/2664412/2f62f242-dccd-4786-90a4-5cbca4c614cf)
4 polygons
![image](https://github.com/scverse/spatialdata/assets/2664412/0ee3ade9-c5e6-41a3-b8be-6c4ab347abe5)
4 multipolygons
![image](https://github.com/scverse/spatialdata/assets/2664412/09429689-5fee-4cd5-af39-316f74bb78b4)
4 points
![image](https://github.com/scverse/spatialdata/assets/2664412/5d848433-f8d3-40a1-8ca8-3a8a7eb757da)

This is with the **new code**.
4 circles
![image](https://github.com/scverse/spatialdata/assets/2664412/ca1cecc7-95b3-4b2e-a706-faff5ebaedfc)
4 polygons
![image](https://github.com/scverse/spatialdata/assets/2664412/328232c1-6587-4dd4-aeb1-de3637713bc9)
4 multipolygons
![image](https://github.com/scverse/spatialdata/assets/2664412/ea410a40-f758-4f90-9708-5ca69425e871)
4 points
![image](https://github.com/scverse/spatialdata/assets/2664412/89dd768a-6bf8-4eea-a882-7c073c8080b6)

Things work, except for points.
I will:
- [ ] check if get_extent() works for points, and if it does report the bug in `spatialdata-plot`
- [ ] open an issue in `spatialdata-plot` to add tests for the cases above; in fact in the tests in `spatialdata` I will just check that the coordinates are correct; I am making the plots now just to see what's going on

**Comment by LucaMarconato** [comment] 2023-10-09 20:41
All correctly computed. I have opened the aforementioned issues in `spatialdata-plot` and I have made a PR to merge against the `get_extent()` PR.

**Comment by LucaMarconato** [comment] 2023-10-10 16:02
Fixed by https://github.com/scverse/spatialdata/pull/373 and merged via https://github.com/scverse/spatialdata/pull/318

**Closed by LucaMarconato** 2023-10-10 16:02 UTC
Labels: bug
