### ISSUE TITLE
sdata does not save when chunks are not equal

### ISSUE THREAD

**Issue by lotte-vandevreken** [scverse/spatialdata#581] opened 2024-06-12 11:17 UTC
When trying to save the sdata to .zarr, it gives an error when the chunks are not equal (for example after cropping the sdata with the bounding_box_query function). The error was fixed after running sdata[image].data = sdata[image].data.rechunk() and sdata[label].data = sdata[label].data.rechunk() for all images and labels.

Maybe this could be added as an extra option to the sdata.write function?

cc. @giovp @lopollar

**Comment by giovp** [comment] 2024-09-08 00:14
I think this could be an issue with the parser

**Comment by LucaMarconato** [comment] 2024-10-03 16:02
I think that this has been addressed by @giovp's PR here https://github.com/scverse/spatialdata/commit/8239455d8abb240dac562dc55511a2bc89822aa4#diff-68732a380479ee7f6980e3662cfbb8eb7bf2713cf5166f6546309a93226869d5R162 with the calls to `.chunk('auto')`.

@lotte-vandevreken could you please verify if the issue is now solved? Thanks 😊

**Comment by lotte-vandevreken** [comment] 2024-10-04 15:16
@LucaMarconato the issue is solved! Thanks!

**Closed** 2024-10-04 22:28 UTC
Labels: API, element: images 🌌
