### ISSUE TITLE
Attempting to write segmented image makes object not saveable.

### ISSUE THREAD

**Issue by LinearParadox** [scverse/spatialdata#464] opened 2024-02-22 09:07 UTC
Using the following code:

```
import squidpy as sq
import spatialdata as sd

def stardist_2D_versatile_he(img, nms_thresh=None, prob_thresh=None):
    # axis_norm = (0,1)   # normalize channels independently
    axis_norm = (0, 1, 2)  # normalize channels jointly
    # Make sure to normalize the input image beforehand or supply a normalizer to the prediction function.
    # this is the default normalizer noted in StarDist examples.
    img = normalize(img, 1, 99.8, axis=axis_norm)
    model = StarDist2D.from_pretrained("2D_versatile_he")
    labels, _ = model.predict_instances(
        img, nms_thresh=nms_thresh, prob_thresh=prob_thresh
    )
    return labels



test=sd.read_zarr("some_zarr.zarr")
test_img=sq.im.ImageContainer(test.images["full_image"]["scale0"]["full_image"])
sq.im.segment(
        img=test_img,
        layer='image',
        channel=None,
        method=stardist_2D_versatile_he,
        layer_added="segmented_stardist_default",
        prob_thresh=None,
        nms_thresh=None,
        lazy=True)
test.images["segmented"]=sd.models.Image2DModel().parse(test_img["segmented_stardist_default"].squeeze(drop=True).expand_dims('c'))
```

now when we try to save this file, it hangs right after writing "test.zarr/images/segmented/0" with 100% cpu use and nothing being written. This is also the case if I use:
```
test.images["segmented"]=sd.models.Image2DModel().parse(test_img["segmented_stardist_default"].squeeze(drop=True).expand_dims({'c':[0]))
```
to make sure c is a coordinate. The same happens if I give c the same coordinates as other images.

**Comment by LucaMarconato** [comment] 2024-02-22 13:25
Hi, thanks for reporting. Cann you please turn this into a minimal reproducible example I can try (for instance by removing the stardist dependency and providing a link to a small public dataset? 

I haven't had this problem with labels before so I would like to try it on my machine. Thanks 😊

**Comment by LucaMarconato** [comment] 2024-02-22 22:01
Thanks for the examples, I have tried and I believe the problem is not when saving but when computing the data. In fact, the code above constructs a lazy representation of the data, which is computed automatically when calling `.write()`.

You can verify by calling `test_img['segmented_default'].compute()`. This will "hang" the code.

@giovp @LLehner can you please comment on the use the image container shown above? Is it expected to take long or is there something to fix in its usage?

## Additional details
- This is to give an idea of the data sizes being handled:
```
test_img["segmented_default"].squeeze(drop=True).expand_dims("c")
Out[10]: 
<xarray.DataArray 'segmented_default' (c: 1, y: 21571, x: 19505)>
dask.array<broadcast_to, shape=(1, 21571, 19505), dtype=uint32, chunksize=(1, 256, 256), chunktype=numpy.ndarray>
Coordinates:
  * y        (y) float64 0.5 1.5 2.5 3.5 ... 2.157e+04 2.157e+04 2.157e+04
  * x        (x) float64 0.5 1.5 2.5 3.5 ... 1.95e+04 1.95e+04 1.95e+04 1.95e+04
Dimensions without coordinates: c
Attributes:
    segmentation:  True
```
- Please notice that there is a typo in the second and third example, the end `}` for the dict should be after the list.

**Comment by LucaMarconato** [comment] 2024-03-23 18:30
> You can verify by calling test_img['segmented_default'].compute(). This will "hang" the code (I see the process is computing with 100% CPU usage).

Due to the bug seemingly not due to `spatialdata` I will close the issue; feel free to reopen it for further discussion.

**Closed by LucaMarconato** 2024-03-23 18:30 UTC
