### ISSUE TITLE
`polygon_query()` cannot filter the table for CODEX data

### ISSUE THREAD

**Issue by GuoshengMa** [scverse/spatialdata#540] opened 2024-04-07 03:02 UTC
Hi @LucaMarconato @melonora ! My spatialdata is CODEX data, and I want to get the table from the input polygon using `polygon_query()`, but the function does not return the table.

Here is my code:

![image](https://github.com/scverse/spatialdata/assets/154969086/4106f168-6968-4dbf-a346-b09fe59a1d5e)

![image](https://github.com/scverse/spatialdata/assets/154969086/5bbd5bea-b803-4ecc-9d26-c1f5352d8fd9)

![image](https://github.com/scverse/spatialdata/assets/154969086/186e75bd-9f1d-46c9-8b35-09bbb25dd872)

I tried the same thing with my 10× visium data and **it works**. So I think it might be **because the `polygon_query()` function cannot recognize the cell coordinate information in the table of CODEX data**.

Here is the files of my CODEX diretory:

![image](https://github.com/scverse/spatialdata/assets/154969086/5b22dcbc-f30a-40d6-bb98-c41462cd7382)

 And here is the table of my CODEX data:

![image](https://github.com/scverse/spatialdata/assets/154969086/51197fe8-c639-4f23-ab38-ec28fd5b3f1f)

**Comment by GuoshengMa** [comment] 2024-04-08 08:34
I think I've found the reason for this issue: there is no information like `cell_boundaries` in `codex_sdata.shape`.

**Comment by melonora** [comment] 2024-04-08 11:53
We don't use obsm anymore so this should not be a problem. With the table that is present in `codex_sdata` could you check what kind of information you have in `table.uns`? For polygon_query to return rows specific to elements, the table must be annotating those particular elements. This is typically specified when parsing the table, but can also be specified later.

**Comment by melonora** [comment] 2024-04-08 11:55
Also in case you want to ask a couple of questions and for us to help you out live I would also like to refer you to our community meetings. Schedule here: https://hackmd.io/enWU826vRai-JYaL7TZaSw. That way you can also get all your questions resolved:)

**Comment by GuoshengMa** [comment] 2024-04-08 12:56
> We don't use obsm anymore so this should not be a problem. With the table that is present in `codex_sdata` could you check what kind of information you have in `table.uns`? For polygon_query to return rows specific to elements, the table must be annotating those particular elements. This is typically specified when parsing the table, but can also be specified later.

I checked the `table.uns` of my visium and codex data, it seems complete, is there any issue here?: 

![image](https://github.com/scverse/spatialdata/assets/154969086/e52e8c95-7214-4918-8add-198b387e88c3)

**Comment by GuoshengMa** [comment] 2024-04-08 12:58
> Also in case you want to ask a couple of questions and for us to help you out live I would also like to refer you to our community meetings. Schedule here: https://hackmd.io/enWU826vRai-JYaL7TZaSw. That way you can also get all your questions resolved:)

Great! Thank you for the invitation! I will attend the community meeting on April 11th as scheduled:D

**Comment by melonora** [comment] 2024-04-08 13:01
So from a quick glance I don't see `20230517-V52L11-399-A1-TMA3-8-outs` as an element in `codex_sdata`. Is that correct?

**Comment by GuoshengMa** [comment] 2024-04-08 13:05
> So from a quick glance I don't see `20230517-V52L11-399-A1-TMA3-8-outs` as an element in `codex_sdata`. Is that correct?

 `20230517-V52L11-399-A1-TMA3-8-outs` is an element in visium `st_sdata`. For `codex_sdata`, this should be 'labels'.

![image](https://github.com/scverse/spatialdata/assets/154969086/f5f27eef-b6a8-48b2-89f1-0281006cd7b5)

**Comment by melonora** [comment] 2024-04-08 13:13
In what coordinate system is the polygon when you assign it to the variable polygon? Did you set the data to be in coordinate system `3D2` before extracting it?

**Comment by GuoshengMa** [comment] 2024-04-08 13:22
> In what coordinate system is the polygon when you assign it to the variable polygon? Did you set the data to be in coordinate system `3D2` before extracting it?

I add a square in shape layer in `3D2` coordinate system:

![image](https://github.com/scverse/spatialdata/assets/154969086/650cb2db-e7c9-4749-8f93-fc4218642b53)

Then I use `polygon_query()` to filter the `codex_sdata`:

![image](https://github.com/scverse/spatialdata/assets/154969086/1089c603-4209-4981-9668-3cb286ffc905)

**Comment by melonora** [comment] 2024-04-08 13:24
ok if none of the others respond before Thursday, lets have a look then.

**Comment by LucaMarconato** [comment] 2024-04-08 16:14
Hi @GuoshengMa, `obsm['spatial']` is not available in general, as it was added just for the Xenium dataset for legacy reasons. You can see more about this here https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/squidpy_integration.html. In particular, the linked notebook we explain how to proceed in general for any dataset if you still need to have `obsm['spatial']`.

**Comment by LucaMarconato** [comment] 2024-04-08 16:22
Regarding the other part of your question, the CODEX data does not contain `cell_boundaries` as this is something specific to Xenium data. In general, CODEX data does not contain polygonal elements as the cell geometries are encoded as a raster type (a "Labels" element). 

Anyway, this should not be a problem because the `polygon_query` function is implemented for shapes, points, polygons and images. I would suggest to open again the data with `napari-spatialdata` and double check that after saving and reopening, the data is indeed under the box. If it is, I would call the `get_extent()` function on each specific element (the ROI, the image, the labels), specifying the desired coordinate system, and checking if the output are bounding boxes that intersect each others. If yes, the problem may be in `polygon_query()`, if not, the problem is somewhere else.

**Comment by GuoshengMa** [comment] 2024-04-09 02:24
> Regarding the other part of your question, the CODEX data does not contain `cell_boundaries` as this is something specific to Xenium data. In general, CODEX data does not contain polygonal elements as the cell geometries are encoded as a raster type (a "Labels" element).
> 
> Anyway, this should not be a problem because the `polygon_query` function is implemented for shapes, points, polygons and images. I would suggest to open again the data with `napari-spatialdata` and double check that after saving and reopening, the data is indeed under the box. If it is, I would call the `get_extent()` function on each specific element (the ROI, the image, the labels), specifying the desired coordinate system, and checking if the output are bounding boxes that intersect each others. If yes, the problem may be in `polygon_query()`, if not, the problem is somewhere else.

@LucaMarconato I tried the method you suggested, but still couldn't get the filtered table.

![image](https://github.com/scverse/spatialdata/assets/154969086/90582508-78d4-4224-8cda-767befc6073c)

![image](https://github.com/scverse/spatialdata/assets/154969086/e1b80c76-5376-48fc-a47b-0ee16d0caba7)

![image](https://github.com/scverse/spatialdata/assets/154969086/2ffe674d-b4f0-4b27-a241-c8e05887dbc4)

**Comment by LucaMarconato** [comment] 2024-04-11 08:16
Thanks for the extra details, that's indeed unexpected. I will look more into this and try to reproduce. Also, in case you are interested we will have a community meeting today: https://scverse.zulipchat.com/#narrow/stream/315824-spatial/topic/spatialdata.20meetings/near/432649742.

**Closed** 2024-04-17 15:34 UTC
