### ISSUE TITLE
Something wrong about annotating regions of interest with napari

### ISSUE THREAD

**Issue by Tony4709** [scverse/spatialdata#551] opened 2024-04-25 00:12 UTC
Hi, 
Thanks for developing such an exciting tools.
I'm trying the process of annotating regions using napari software follow the tutorial https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/napari_rois.html, but I found some results do not make sense.
This is my shape in napari
<img width="216" alt="image" src="https://github.com/scverse/spatialdata/assets/148491569/5d69c6d1-e74d-4cf8-b9f9-2fb005039585">
But after querying, the result is 
<img width="211" alt="image" src="https://github.com/scverse/spatialdata/assets/148491569/2c44135d-6589-4226-a3d4-7656e10766df">
I think there are something wrong in spatial coordinate?

Thanks again 

Best,
Tony

**Comment by LucaMarconato** [comment] 2024-07-10 18:22
I will close the issue as we can't reproduce it: I have just run the notebook using the latest version and it does not seem to display this problem.

Feel free to reopen if you find that this issue persists, in such a case please provide additional details on the versions you are using (you can use the command `pip list | grep spatialdata`), and explaning how to reproduce the behavior.

**Closed by LucaMarconato** 2024-07-10 18:22 UTC
